version: '1.0'

services:

  my-app:
    container_name: clinic-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:8080'